### ISSUE TITLE
pt->onnx->ncnn

### ISSUE THREAD

**Issue by chenzj-king** [xiang-wuu/ncnn-android-yolov7#2]
I use yolov7 models/export.py export xx.pt to xx.onnx. But use this xx.onnx not work

```
$ ./onnx2ncnn.exe test.onnx test.parma test.bin
Identity not supported yet!
Unknown data type 0
Unsupported Resize scales and sizes are all empty!
```

Can you give me some guide? 
Thanks

**Comment by xiang-wuu** [comment]
while exporting to onnx you need to enable the `--grid` option,
`python export.py --weights yolov7.pt --grid`
and then simplify the onnx model as below,
`onnxsim yolov7.onnx yolov7-simpl.onnx `

**Comment by chenzj-king** [comment]
I use yolov7 export.py get xx.torchscript.pt. pnnx exchange to xx.bin and xx.param
