### ISSUE TITLE
problem using custom weights

### ISSUE THREAD

**Issue by SnowNation101** [xiang-wuu/ncnn-android-yolov7#7]
Hi, thank you for the awesome demo！
I have a few questions about using cutom weights
1. There are some errors when exporting onnx to ncnn : `Unsupported slice axes !`, and the result can't be used in detection
2. Can I use models other than yolov7-tiny? If so , do I need to change any code besides replacing the assets?
Thanks!

**Comment by xiang-wuu** [comment]
no need to change the code for other model variant!

**Comment by SnowNation101** [comment]
@xiang-wuu thank you so much! if I want to use this demo to detect grayscale videos with a model input size 1*640*640, where should i change to fit this model ? sorry if these questions sounds stupid 😭

**Comment by jhony2507** [comment]
> Hi, thank you for the awesome demo！ I have a few questions about using cutom weights
> 
> 1. There are some errors when exporting onnx to ncnn : `Unsupported slice axes !`, and the result can't be used in detection
> 2. Can I use models other than yolov7-tiny? If so , do I need to change any code besides replacing the assets?
>    Thanks!

were you able to convert your weights from onnx to ncnn? I have the same problem.

**Comment by dadin852** [comment]
@xiang-wuu May I ask how to use my own model?
